export interface QelarixModel {
  id: string
  name: string
  provider: string
  type: 'image' | 'video' | 'audio'
  credits: number
  description: string
  tags: string[]
  badges: string[]
  falId: string  // legacy/display-only catalog metadata — NOT read at runtime (image route uses src/lib/image-models.ts falEndpoint via the IMAGE_MODEL_IDS bridge). Keep truthful; it has no runtime effect.
  logoUrl?: string  // URL or path to the model logo
  /** Phase1 catalog-truth: when true, hidden from selectable model lists everywhere */
  comingSoon?: boolean
}

export const QELARIX_MODELS: QelarixModel[] = [
  // ── IMAGE ──
  { id: 'sd35', name: 'Stable Diffusion 3.5', provider: 'Stability', type: 'image', credits: 2, description: 'Fast, reliable image generation for everyday creative work.', tags: ['General', '1K'], badges: [], falId: 'fal-ai/stable-diffusion-v35-large' },
  { id: 'nano_banana2', name: 'Nano Banana 2', provider: 'Google', type: 'image', credits: 4, description: 'Fast Google image model with accurate text rendering; resolution selectable (1K/2K/4K).', tags: ['1K–4K', 'Text Rendering', 'Fast'], badges: [], falId: 'fal-ai/nano-banana-2' }, // base 1K = 4 credits; 2K = 6; 4K = 8 (via resolution tiers); falId matches source-of-truth code key nanobanana2
  { id: 'imagen4', name: 'Imagen 4 Fast', provider: 'Google', type: 'image', credits: 3, description: 'Google Imagen 4 — photorealistic quality at high speed.', tags: ['4K', 'Photorealistic'], badges: ['NEW'], falId: 'fal-ai/imagen4/preview/fast' }, // served endpoint = imagen4/preview/fast (slug 'imagen4' → backend 'imagen4fast')
  { id: 'flux2_pro', name: 'FLUX 2 Pro', provider: 'Black Forest Labs', type: 'image', credits: 2, description: 'FLUX.2 Pro — studio-grade detail and color accuracy.', tags: ['2K', 'Professional'], badges: ['NEW'], falId: 'fal-ai/flux-2-pro' }, // v1.2 rollout: served fal-ai/flux-2-pro (provider-verified, $0.03/MP); internal slug 'flux2pro' is a stable credits/mapping key (do not rename)
  { id: 'ideogram3', name: 'Ideogram V3', provider: 'Ideogram', type: 'image', credits: 3, description: 'Best-in-class text rendering inside images.', tags: ['Text Rendering', '2K'], badges: [], falId: 'fal-ai/ideogram/v3' },
  { id: 'recraft_v4', name: 'Recraft V3', provider: 'Recraft', type: 'image', credits: 5, description: 'Vector-quality SVG and raster images with style control.', tags: ['SVG', 'Design'], badges: [], falId: 'fal-ai/recraft/v3/text-to-image' }, // label 'Recraft V3' = served v3; UI id 'recraft_v4' → stable backend slug 'recraft' (do not rename)
  { id: 'gpt_image2', name: 'GPT Image 2', provider: 'OpenAI', type: 'image', credits: 4, description: 'OpenAI gpt-image-2 — flagship image model with quality tiers (Fast / Standard / Ultra).', tags: ['Instruction', 'Quality Tiers'], badges: ['PREMIUM'], falId: 'openai/gpt-image-2' }, // v1.2 integration 2026-06-03: REAL OpenAI gpt-image-2 (direct Images API, NOT DALL·E, NO fallback). Bridge gpt_image2 → runtime gptimage2; credits=GPT Standard (medium)=4. 'Edit' deferred.
  { id: 'nano_banana_pro', name: 'Nano Banana Pro', provider: 'Google', type: 'image', credits: 8, description: 'Top-tier 4K images with precise multilingual text rendering.', tags: ['4K', 'Text Rendering', 'PRO'], badges: ['PREMIUM'], falId: 'fal-ai/nano-banana-pro' }, // '4K' dropped from label (not wired in route); falId corrected from a stale Imagen value to the real endpoint
  { id: 'flux2_max', name: 'FLUX 1.1 Pro Ultra', provider: 'Black Forest Labs', type: 'image', credits: 3, description: 'Maximum detail for intricate compositions and demanding scenes.', tags: ['2K', 'Detail'], badges: [], falId: 'fal-ai/flux-pro/v1.1-ultra' }, // label = served v1.1-ultra; slug 'flux2max' is a stable key (do not rename)
  { id: 'flux_kontext', name: 'FLUX Kontext Pro', provider: 'Black Forest Labs', type: 'image', credits: 20, description: 'Edit and compose from up to 4 reference images with context awareness.', tags: ['Edit', 'Multi-Image', '2K'], badges: [], falId: 'fal-ai/flux-pro/kontext', comingSoon: true }, // Hidden from Playground image picker: not in source-of-truth (no kontext endpoint in code). Do NOT silently route to flux2pro.
  { id: 'grok_imagine', name: 'Grok Imagine', provider: 'xAI', type: 'image', credits: 4, description: 'Grok by xAI — bold, expressive, photorealistic image generation.', tags: ['Photorealistic', 'PRO'], badges: ['PREMIUM'], falId: 'xai/grok-2-image' }, // served = xAI grok-2-image (direct API, not fal). Selectable per source-of-truth (Code Mapping VERIFIED OK); 501 if XAI_API_KEY missing.
  { id: 'seedream5', name: 'Seedream 4.0', provider: 'ByteDance', type: 'image', credits: 2, description: 'ByteDance Seedream 4.0 — cinematic quality with deep scene understanding.', tags: ['Cinematic', '2K'], badges: [], falId: 'fal-ai/bytedance/seedream/v4/text-to-image' }, // v1.2 rollout: served seedream v4 (provider-verified, $0.03/img); credits=CREDITS.image.seedream5=2
  { id: 'seedream45', name: 'Seedream 4.5', provider: 'ByteDance', type: 'image', credits: 2, description: 'ByteDance Seedream 4.5 — newer model with stronger text rendering and character consistency.', tags: ['Cinematic', '2K'], badges: ['NEW'], falId: 'fal-ai/bytedance/seedream/v4.5/text-to-image' }, // v1.2: served seedream v4.5 (provider-verified, $0.04/img); credits=CREDITS.image.seedream45=2 (2K only; 4K/Edit deferred)
  // ── VIDEO ──
  { id: 'wan26', name: 'Wan 2.6', provider: 'Wan', type: 'video', credits: 10, description: 'Affordable, fast video generation. Best starting point.', tags: ['5s', '10s', '16:9'], badges: [], falId: 'fal-ai/wan-video', comingSoon: true }, // SUPERSEDED by Wan 2.2 (no real "Wan 2.6" endpoint; fal-ai/wan-video → 404). Kept hidden.
  { id: 'wan22', name: 'Wan 2.2', provider: 'Wan', type: 'video', credits: 32, description: 'Alibaba Wan 2.2 — high-quality text-to-video, up to 10s. Resolution selectable in the prompt box.', tags: ['5s', '10s', '480p–720p'], badges: [], falId: 'fal-ai/wan/v2.2-a14b/text-to-video' }, // ONE Wan 2.2 family (picker-normalized 2026-06-02). Quality (480p/580p/720p) is chosen in the prompt box → qualityVariants map (runtime wan22_480/wan22_580/wan22) drives price+payload. credits = 720p default (5s); live cost follows the selected quality. Interim per-res picker rows removed; runtime entries + price keys kept.
  { id: 'wan25', name: 'Wan 2.5', provider: 'Wan', type: 'video', credits: 100, description: 'Alibaba Wan 2.5 (preview) — premium text-to-video up to 1080p.', tags: ['5s', '10s', '1080p'], badges: [], falId: 'fal-ai/wan-25-preview/text-to-video', comingSoon: true }, // COMING SOON 2026-06-02: preview (non-GA) endpoint verified; premium roadmap. Hidden until GA + final pricing/audio. MASTER has full COMING SOON pricing.
  { id: 'ltx2', name: 'LTX 2.0', provider: 'Lightricks', type: 'video', credits: 8, description: 'Smooth motion with excellent prompt adherence.', tags: ['5s', '16:9', '9:16'], badges: [], falId: 'fal-ai/ltx-video' }, // falId fixed to canonical (verified 200); credits aligned with VIDEO_PRICES.ltx2[5].no=10
  { id: 'luma_ray3', name: 'Luma Ray 3', provider: 'Luma AI', type: 'video', credits: 30, description: 'Cinematic quality, stunning lighting, lifelike motion.', tags: ['5s', 'Cinematic'], badges: [], falId: 'fal-ai/luma-dream-machine/ray-2' },
  { id: 'pika25', name: 'Pika 2.1', provider: 'Pika', type: 'video', credits: 12, description: 'Creative and expressive video generation with character consistency.', tags: ['5s', 'Creative'], badges: [], falId: 'fal-ai/pika/v2.1/text-to-video' }, // falId fixed to canonical (verified 200); label aligned with Phase 1; credits=VIDEO_PRICES.pika25[5].no=20
  { id: 'kling3', name: 'Kling 3.0', provider: 'Kuaishou', type: 'video', credits: 30, description: 'Multi-shot cinematic sequences — best-value text-to-video.', tags: ['5s', '10s', 'Cinematic', 'PRO'], badges: ['EXCLUSIVE'], falId: 'fal-ai/kling-video/v3/standard/text-to-video' }, // falId synced to verified served v3 endpoint (display-only; runtime uses video-models.ts)
  { id: 'kling3_pro', name: 'Kling 3.0 Pro', provider: 'Kuaishou', type: 'video', credits: 50, description: 'Maximum quality Kling with hyper-realistic motion and 10s support.', tags: ['5s', '10s', 'PRO'], badges: ['PREMIUM'], falId: 'fal-ai/kling-video/v3/pro/text-to-video' }, // falId synced to verified served v3 endpoint (display-only)
  { id: 'kling3_4k', name: 'Kling V3 4K', provider: 'Kuaishou', type: 'video', credits: 106, description: 'Ultra-HD 4K video up to 15s with native audio.', tags: ['4K', '15s', 'Audio'], badges: ['PREMIUM'], falId: 'fal-ai/kling-video/v3/4k/text-to-video', logoUrl: 'https://ai.kling.kuaishou.com/favicon.ico' }, // falId synced to verified served v3/4k endpoint (display-only)
  { id: 'kling3_standard', name: 'Kling V3 Standard', provider: 'Kuaishou', type: 'video', credits: 25, description: 'Balanced speed and quality for everyday video generation.', tags: ['1080p', '15s', 'Audio'], badges: [], falId: 'fal-ai/kling-video/v3/standard/text-to-video', logoUrl: 'https://ai.kling.kuaishou.com/favicon.ico' }, // falId synced to verified served v3 endpoint (display-only)
  { id: 'kling26_pro', name: 'Kling V2.6 Pro', provider: 'Kuaishou', type: 'video', credits: 30, description: 'Mature pipeline with audio, adjustable cfg, and standard/pro rendering.', tags: ['1080p', '5/10s', 'Audio', 'Start/End Frame'], badges: [], falId: 'fal-ai/kling-video/v2.6/pro/text-to-video', logoUrl: 'https://ai.kling.kuaishou.com/favicon.ico' },
  { id: 'kling26_standard', name: 'Kling V2.6 Standard', provider: 'Kuaishou', type: 'video', credits: 18, description: 'Reliable 5-10s video with cfg scale control and rendering speed options.', tags: ['1080p', '5/10s', 'Audio', 'Start/End Frame'], badges: [], falId: 'fal-ai/kling-video/v2.6/standard/text-to-video', logoUrl: 'https://ai.kling.kuaishou.com/favicon.ico', comingSoon: true }, // DISABLED 2026-06-06: fal-ai/kling-video/v2.6/standard/text-to-video public docs 404 (model/playground/api) while v2.6 Pro exists; v2.6 Standard appears to be motion-control (v2v) only. Hidden from the Playground picker until the endpoint is officially verified. Runtime config / credits / bridge kept intact (no price set until validated).
  { id: 'kling3_omni', name: 'Kling V3 Omni', provider: 'Kuaishou', type: 'video', credits: 35, description: 'Flexible generation across creative styles using V3 Omni architecture.', tags: ['HD', '15s'], badges: ['NEW'], falId: 'fal-ai/kling-video/v3/pro/text-to-video', logoUrl: 'https://ai.kling.kuaishou.com/favicon.ico' }, // falId synced to verified served v3/pro endpoint (shares endpoint with kling3_pro; display-only)
  { id: 'kling_o1_reference', name: 'Kling O1', provider: 'Kuaishou', type: 'video', credits: 25, description: 'Reference-to-video with multiple image references for subject/character consistency.', tags: ['5s', '10s', 'Reference', 'Character'], badges: ['PREMIUM'], falId: 'fal-ai/kling-video/o1/reference-to-video', logoUrl: 'https://ai.kling.kuaishou.com/favicon.ico' }, // v1.2 rollout 2026-06-07: real reference-to-video (image_urls[]); credits=VIDEO_PRICES.kling_o1_reference[5].no=25 (same id catalog↔runtime; no bridge rename)
  { id: 'seedance2', name: 'Seedance 2.0', provider: 'ByteDance', type: 'video', credits: 76, description: 'Cinematic video with native AI audio track generation.', tags: ['5s', 'Audio', 'Cinematic'], badges: ['NEW'], falId: 'bytedance/seedance-2.0/text-to-video' }, // falId fixed to canonical (verified 200); credits=VIDEO_PRICES.seedance20[5].no=76 (VIDEO_MODEL_IDS maps seedance2→seedance20)
  { id: 'seedance2_fast', name: 'Seedance 2.0 Fast', provider: 'ByteDance', type: 'video', credits: 61, description: 'Faster, lower-cost Seedance 2.0 with native AI audio.', tags: ['5s', '10s', 'Audio'], badges: [], falId: 'bytedance/seedance-2.0/fast/text-to-video' }, // Group 1 rollout: distinct UI id (seedance2 is taken by Seedance 2.0→seedance20); bridged to runtime seedance2; credits=VIDEO_PRICES.seedance2[5].no=61 (display-only)
  { id: 'grok_video', name: 'Grok Imagine Video', provider: 'xAI', type: 'video', credits: 30, description: 'xAI Grok Imagine — expressive, physics-aware video with native audio. Resolution selectable in the prompt box.', tags: ['5s', '15s', 'Audio', '480p–720p'], badges: ['PREMIUM'], falId: 'xai/grok-imagine-video/text-to-video' }, // ONE Grok family (picker-normalized 2026-06-02). Quality (480p/720p) chosen in prompt box → qualityVariants (runtime grokvideo480/grokvideo) drives price+payload; audio native/included. credits = 720p default (5s). Interim 480p picker row removed; runtime entry + price key kept.
  { id: 'happy_horse', name: 'Happy Horse 1.0', provider: 'Happy Horse', type: 'video', credits: 30, description: 'Character-driven animated video with consistent style.', tags: ['5s', 'Animation'], badges: [], falId: 'fal-ai/haiper-video-v2', comingSoon: true }, // Phase1 catalog-truth: Haiper endpoint unverified/unreliable
  { id: 'veo4', name: 'Veo 2', provider: 'Google', type: 'video', credits: 110, description: 'Google Veo 2 — photorealistic cinematic video with native audio.', tags: ['5s', 'Cinematic'], badges: [], falId: 'fal-ai/veo2' },
  { id: 'veo31_standard', name: 'Veo 3.1', provider: 'Google', type: 'video', credits: 40, description: 'Google DeepMind Veo 3.1 — high-fidelity video with native audio (4-8s).', tags: ['4s', '8s', 'Audio'], badges: ['PREMIUM'], falId: 'fal-ai/veo3.1' }, // Group 1 rollout: bridged via VIDEO_MODEL_IDS to runtime veo31_standard; credits=VIDEO_PRICES.veo31_standard[4].no=40 (display-only)
  { id: 'veo31', name: 'Veo 3.1 Fast', provider: 'Google', type: 'video', credits: 20, description: 'Google DeepMind Veo 3.1 Fast — faster, lower-cost video with native audio (4-8s).', tags: ['4s', '8s', 'Audio'], badges: [], falId: 'fal-ai/veo3.1/fast' }, // Group 2 rollout: bridged to runtime veo31 (endpoint verified 200); credits=VIDEO_PRICES.veo31[4].no=20 (display-only)
  { id: 'veo3', name: 'Veo 3', provider: 'Google', type: 'video', credits: 76, description: 'Google Veo 3 — cinematic video with optional native audio (4-8s). Audio on/off in the prompt box.', tags: ['4s', '8s', 'Audio on/off'], badges: ['NEW'], falId: 'fal-ai/veo3' }, // ONE Veo 3 family (picker-normalized 2026-06-02). Audio on/off is the prompt-box toggle → veo3 no/yes price column + generate_audio. credits = audio-ON default (4s); live cost follows the toggle. Interim 'Veo 3 (Silent)' picker row removed; runtime entry + price key kept.
  { id: 'sora2', name: 'Sora 2', provider: 'OpenAI', type: 'video', credits: 24, description: 'OpenAI Sora 2 — cinematic text-to-video with native audio (4-20s).', tags: ['4s', '20s', 'Audio'], badges: ['PREMIUM'], falId: 'fal-ai/sora-2/text-to-video' }, // ACTIVE 2026-06-02: prompt-only (character_ids optional); bridged sora2→sora2 (endpoint verified 200, duration 4/8/12/16/20s); credits=VIDEO_PRICES.sora2[4].no=24
  { id: 'sora2pro', name: 'Sora 2 Pro', provider: 'OpenAI', type: 'video', credits: 65, description: 'OpenAI Sora 2 Pro — premium cinematic text-to-video with native audio (720p, 4-20s).', tags: ['4s', '20s', 'Audio', 'Pro'], badges: ['PREMIUM'], falId: 'fal-ai/sora-2/text-to-video/pro' }, // ACTIVE 2026-06-02: prompt-only; bridged sora2pro→sora2pro (verified 200, 4/8/12/16/20s; route forces 720p); credits=VIDEO_PRICES.sora2pro[4].no=65
  // ── AUDIO ──
  { id: 'stability_audio', name: 'Stability Audio', provider: 'Stability AI', type: 'audio', credits: 20, description: 'AI music & sound generation — choose the length (30s / 1 min / 2 min) in the prompt bar.', tags: ['Music', '30s–2min'], badges: [], falId: 'stability-audio-30s' }, // ONE Stability Audio family (picker-normalized). Length (30/60/120s) is an in-box control → CREDITS.audio tier; the route derives the model from duration. credits = 30s from-price.
  { id: 'stability_2min', name: 'Stability Audio 2min', provider: 'Stability AI', type: 'audio', credits: 80, description: 'Full 2-minute AI music track with consistent style and mood.', tags: ['2min', 'Music', 'PRO'], badges: [], falId: 'stability-audio-2min', comingSoon: true }, // Superseded by the Stability Audio family + in-box Length control (2 min = 120s option). Hidden from the picker; not deleted.
  // ── Audio batch v1.2 (unified: src/lib/audio-models.ts + CREDITS.audio). id === audio-models id === audio route `model` param. ──
  { id: 'eleven_v3', name: 'ElevenLabs v3', provider: 'ElevenLabs', type: 'audio', credits: 6, description: 'Expressive text-to-speech. Up to 1000 characters per generation.', tags: ['TTS', 'Voice'], badges: ['NEW'], falId: 'fal-ai/elevenlabs/tts/eleven-v3' }, // TTS; flat per-gen CREDITS.audio.eleven_v3; prompt = text (<=1000 chars), no length control.
  { id: 'eleven_multilingual_v2', name: 'ElevenLabs Multilingual v2', provider: 'ElevenLabs', type: 'audio', credits: 6, description: 'Stable multilingual text-to-speech. Up to 1000 characters.', tags: ['TTS', 'Multilingual'], badges: [], falId: 'fal-ai/elevenlabs/tts/multilingual-v2' }, // TTS; flat CREDITS.audio.eleven_multilingual_v2; prompt = text.
  { id: 'lyria2', name: 'Lyria 2', provider: 'Google', type: 'audio', credits: 8, description: 'Google Lyria 2 — cinematic instrumental music (~30s).', tags: ['Music', '30s'], badges: ['NEW'], falId: 'fal-ai/lyria2' }, // Music; flat CREDITS.audio.lyria2; fixed ~30s, prompt-only.
  { id: 'ace_step', name: 'ACE-Step', provider: 'ACE-Step', type: 'audio', credits: 8, description: 'Generate songs from style tags, with optional lyrics (≤60s / ≤120s).', tags: ['Song', 'Lyrics'], badges: [], falId: 'fal-ai/ace-step' }, // Song; tiered CREDITS.audio.ace_step_60/120 via duration control; optional lyrics + instrumental in Playground UI.
  { id: 'elevenlabs_music', name: 'ElevenLabs Music', provider: 'ElevenLabs', type: 'audio', credits: 40, description: 'Premium full-song generation — vocals or instrumental, 1–3 min.', tags: ['Song', 'Music'], badges: ['PREMIUM'], falId: 'fal-ai/elevenlabs/music' }, // Async full-song; tiered CREDITS.audio.elevenlabs_music_1m/2m/3m via duration control; from-price = 1 min (40).
  { id: 'suno_generate_sounds', name: 'Suno Generate Sounds', provider: 'Suno', type: 'audio', credits: 8, description: 'Sound-effect generation. Coming soon.', tags: ['SFX'], badges: [], falId: 'suno-generate-sounds', comingSoon: true }, // COMING_SOON: muapi audio submit/status flow not wired. Catalogued + priced (provisional) in MASTER + audio-models.ts.
]

// Phase1 catalog-truth: comingSoon models are excluded from all selectable lists.
export const getModelsByType = (type: 'image' | 'video' | 'audio') =>
  QELARIX_MODELS.filter(m => m.type === type && !m.comingSoon)

export const getFeaturedModels = () =>
  QELARIX_MODELS.filter(m => (m.badges.includes('EXCLUSIVE') || m.badges.includes('PREMIUM')) && !m.comingSoon)

export const getNewModels = () =>
  QELARIX_MODELS.filter(m => m.badges.includes('NEW') && !m.comingSoon)

export const providerColor: Record<string, string> = {
  'Google': '#4285F4',
  'OpenAI': '#10A37F',
  'Black Forest Labs': '#FF6B35',
  'xAI': '#1DA1F2',
  'ByteDance': '#FE2C55',
  'Kuaishou': '#FF4500',
  'Stability AI': '#7B61FF',
  'Stability': '#7B61FF',
  'Luma AI': '#9C27B0',
  'Lightricks': '#E91E63',
  'Wan': '#00BCD4',
  'Pika': '#FF9800',
  'Happy Horse': '#4CAF50',
  'Ideogram': '#F44336',
  'Recraft': '#607D8B',
}
