[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
qelarix_qlc = "EtqwjEQT2ZuEwFZ9RXoPgDbupn7eH8iLyV3cR2ENrwNa"

[programs.localnet]
qelarix_qlc = "EtqwjEQT2ZuEwFZ9RXoPgDbupn7eH8iLyV3cR2ENrwNa"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
