import { Metadata } from "next";
import Link from "next/link";
import QelarixBackdrop from "@/components/ui/QelarixBackdrop";

export const metadata: Metadata = {
  title: "Legal notice — Qelarix",
  description: "Legal notice and provider information for Qelarix.",
  robots: { index: false, follow: false },
};

const EMAIL = "contact@pixidigital.io";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-lg font-semibold text-white mb-3">{title}</h2>
      <div className="text-white/65 text-sm leading-7 space-y-2">{children}</div>
    </div>
  );
}

export default function LegalNoticePage() {
  return (
    <div className="min-h-screen">
      <QelarixBackdrop layer="behind" />
      <div className="border-b" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
        <div className="max-w-3xl mx-auto px-6 py-5 flex items-center justify-between">
          <Link href="/" className="text-white/60 hover:text-white text-sm transition-colors flex items-center gap-2">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="m15 18-6-6 6-6" />
            </svg>
            Back
          </Link>
          <span className="text-white/30 text-xs">Last updated: October 2026</span>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-white mb-2">Legal notice</h1>
          <p className="text-white/40 text-sm">Provider information (Impressum)</p>
        </div>

        <Section title="Provider">
          <p>Qelarix, a project by Pixi Digital</p>
          <p>Founder: Pixi</p>
        </Section>

        <Section title="Project status">
          <p>
            Qelarix is a non-commercial beta. It runs on the Solana devnet, where QLC and other tokens have no monetary
            value. No payments with real money are processed.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Email:{" "}
            <a href={`mailto:${EMAIL}`} className="text-purple-400 hover:text-purple-300">{EMAIL}</a>
          </p>
          <p>For privacy requests, please use the same address.</p>
        </Section>

        <Section title="Liability for content">
          <p>
            We create the content of this site with care, but we cannot guarantee that it is complete, accurate or
            current. Content generated by users with AI models is the responsibility of the user who created and
            published it. If you notice unlawful content, please contact us and we will remove it promptly.
          </p>
        </Section>

        <Section title="Liability for links">
          <p>
            This site may link to external websites. We have no influence on their content and are not responsible for
            it. If we become aware of unlawful content on a linked site, we will remove the link.
          </p>
        </Section>

        <Section title="Copyright">
          <p>
            The Qelarix name, logo and site design may not be copied or reused without permission. Users keep the
            rights they hold in their own prompts and uploads, as described in the Terms of Service.
          </p>
        </Section>

        <div className="pt-6 border-t flex gap-6 text-sm" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
          <Link href="/privacy-policy" className="text-white/40 hover:text-white/70 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="text-white/40 hover:text-white/70 transition-colors">Terms of Service</Link>
        </div>
      </div>
    </div>
  );
}
